# Generated by Django 3.2.7 on 2022-12-19 15:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20221219_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
