# Generated by Django 3.2.7 on 2022-12-20 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0018_alter_productreview_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='author',
            field=models.ForeignKey(default=1, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
