# Generated by Django 3.2.7 on 2022-12-31 15:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20221220_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default=3, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimages',
            name='thumbnail',
            field=models.ImageField(default=4, upload_to='images/'),
            preserve_default=False,
        ),
    ]
