# Generated by Django 3.2.7 on 2022-12-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20221231_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='name',
        ),
    ]
