# Generated by Django 3.2.7 on 2022-08-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_intent',
        ),
    ]
