# Generated by Django 3.2.7 on 2023-01-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='conf_num',
            field=models.CharField(default=1478235654, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
