# Generated by Django 3.2.7 on 2023-01-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
