# Generated by Django 3.2.7 on 2022-12-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20221217_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
